/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2024. All rights reserved.
 * Generated by the Cloud Object compiler. DO NOT EDIT!
 */
import type { BusinessError } from '@kit.BasicServicesKit';
import { cloudFunction } from '@kit.CloudFoundationKit';

export interface CloudObjectLikely {
  name: string;
}

function mockMethod<T extends CloudObjectLikely>(target: T, version: string,
  prop: string | symbol): (...args: unknown[]) => Promise<unknown> {
  return async (...args: unknown[]) => new Promise((resolve, reject) => {
    cloudFunction.call({
      name: target.name,
      version: version,
      data: {
        method: prop,
        params: args
      }
    }).then((value: cloudFunction.FunctionResult) => {
      resolve(value.result);
    }).catch((err: BusinessError) => {
      reject(err);
    });
  });
}

export function importObject<T extends CloudObjectLikely>(tClass: new () => T, version = '$latest'): T {
  return new Proxy<T>(new tClass(), {
    get(target, prop): (...args: unknown[]) => Promise<unknown> {
      return mockMethod<T>(target, version, prop);
    }
  });
}
