/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2024. All rights reserved.
 * Generated by the Cloud Object compiler. DO NOT EDIT!
 */
import type { CloudObjectLikely } from '../ImportObject';

export class IdGenerator implements CloudObjectLikely {
    name = 'id-generator';

    async randomUUID(): Promise<{
        uuid: `${string}-${string}-${string}-${string}-${string}`;
    }> {
        return Promise.reject(new Error('Method not implemented.'));
    }
}

